#!/bin/bash

pidfile="/tmp/lights.pid"
dir=$(dirname "$0")

if test -f "$pidfile"; then
    pid=$(cat "$pidfile")
    if ps -p $pid > /dev/null; then
        kill -9 "$pid"
    fi
fi

scripts=(
    "all_on.py"
    "in_out.py"
    "random_leds.py"
    "slow_walk.py"
    "twinkle.py"
    "track.py"
    "twinkle.py"
)
script=${scripts[$RANDOM % ${#scripts[@]} ]}

python3 "$dir/../$script" &

echo $! > $pidfile
